### ISSUE TITLE
cdb_moran_local_rate should accept queries as input

### ISSUE THREAD

**Issue by rochoa** [CartoDB/crankshaft#6] opened 2016-03-07 10:57 UTC
I would expect to pass a query like `(select * from working_from_home) _cdb_moran_target`

```sql
select * from
cdb_crankshaft.cdb_moran_local_rate('(select * from working_from_home) _cdb_moran_target',
                   'worked_at_home', 'workers_16_years_and_over',
                   0.05, 5, 999, 'the_geom', 'cartodb_id', 'queen')
```

But it fails because the *table* name is being quoted like 

```sql
FROM "(select * from working_from_home) _cdb_moran_target"
```

Maybe it's a long shoot but I think it makes sense to accept queries as input instead of just tables, because in some cases that means that you always have to create a table: imagine that I want to just filter by other column, e.g. per capita income > 30k, I need to create a table just to be able to call `cdb_moran_local_rate`.

**Comment by rochoa** [comment] 2016-03-07 10:57
cc @javisantana

**Comment by javisantana** [comment] 2016-03-07 11:05
Hey, 

cdb_moran_local_rate function has 2 important issues we need to address before going to production.

1) performance is really really bad, we need to improve by 100x before hitting production servers

2) I don't agree about the interface, it should be a window function. This is a clustering thing and that's the way should work. Please, check this thread https://lists.osgeo.org/pipermail/postgis-devel/2015-December/025499.html

It should look like:

```
SELECT id, geom, cdb_moran_local_rate(geom, whatever, ...) OVER (ORDER BY whatever_thing)  FROM table;
```

**Comment by javisantana** [comment] 2016-03-07 11:15
cc @andrewxhill @ohasselblad

**Comment by ohasselblad** [comment] 2016-03-07 14:40
One wall that I'll hit by doing a windows function is that this function needs to return two values for each geometry: classification (HH, HL, LH, LL) and significance (a number 0-1). That's the reason why I formatted the interface like a table-returning function..

**Comment by ohasselblad** [comment] 2016-03-07 15:41
@javisantana, on point 1, I'll prepare a fork that runs much faster. The problem is a `numpy.shuffle` in the [pysal source](https://github.com/pysal/pysal/blob/03b1352d93b384b9d8cc8eb32725d264fde16c71/pysal/esda/moran.py#L682) that scales pretty badly depending on the number of things to be clustered. I'm open to a CR for advice on other things to speed up.

For point 2, it seems that windows functions can only be developed in C (not PL/pgSQL or PL/Python)? We want to rely on PL/Python to expose PySAL. If we can do in PL/Python, I could modify so that it would work in windows functions -- I found a way around my concern in the previous comment.

**Comment by ohasselblad** [comment] 2016-03-30 16:14
@javisantana, do you still think we should do a window function for this? Our goal here was to lean on the PySAL library to get the functionality. My understanding of window functions is that they need to be written in C.

**Comment by ohasselblad** [comment] 2016-03-30 16:15
BTW, I updated the function to take in arbitrary queries now: https://github.com/CartoDB/crankshaft/pull/19

**Comment by javisantana** [comment] 2016-03-30 16:38
that would be the ideal, not a requirement

**Comment by ohasselblad** [comment] 2016-03-30 16:44
for the record this is how it'll be used probably (grabbing more than one new column):

```sql
SELECT
  o.*,
  c.cluster_type,
  c.signif as significance_of_cluster
FROM
  original_table as o
JOIN
  CDB_AreasOfInterest('crazy query', 'interesting_column') As c(moran, signif, cluster_type, original_var, ids)
ON o.cartodb_id = c.ids;
```

**Comment by ohasselblad** [comment] 2016-05-20 20:29
Closing this as this is now the standard format for doing all of our functions and is being added as a checklist item for code review: https://github.com/CartoDB/crankshaft/pull/56

**Closed by ohasselblad** 2016-05-20 20:29 UTC
